[package]
name = "rust-write-file"
version = "0.1.0"
authors = ["Christophe Rosset <tophe@topheman.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
